### ISSUE TITLE
Include version to the UA header to identify the provider and its version

### ISSUE THREAD

**Issue by drsm79** [EnterpriseDB/terraform-provider-biganimal#47]
We should have a/some HTTP header(s) which:

- clearly identifies the request as coming from the provider
- records version of teraform
- records version of provider

I think this should be [added here](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/pkg/api/api.go#L17)

**Comment by drsm79** [comment]
The user-agent identifies the request as coming from the provider, but not versions.

**Comment by serdardalgic** [comment]
Actually, the headers are added when the request is being prepared. That's why the user agent is set during the doRequest function here https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/pkg/api/request.go#L19.

The constant that's set is defined inside the [cluster_client.go](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/pkg/api/cluster_client.go#L14) 

I don't know how, but we can get [this version string](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/main.go#L20) (this can also be set by goreleaser while we're preparing the release packages) and we can add this version string to the end of the constant) 

@nstott any thoughts on that?
