### ISSUE TITLE
Repeated terraform apply reports "1 changed" in the output even though there are no changes in TF files.

### ISSUE THREAD

**Issue by ftouserkani-edb** [EnterpriseDB/terraform-provider-biganimal#98]
**% terraform -v**
```
Terraform v1.3.6
on darwin_amd64
```
**### Terraform Configuration Files**
```
terraform {
  required_providers {
    biganimal = {
      source  = "EnterpriseDB/biganimal"
      version = "0.1.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.3.1"
    }
  }
}

resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "{}{}()"
  min_lower        = 3
  min_numeric      = 5
  min_special      = 3
  min_upper        = 2
}

resource "random_string" "test" {
  length = 20
  special          = true
  override_special = "/@£$?"
  min_lower        = 5
  min_numeric      = 5
  min_upper        = 5
  min_special      = 5
}

resource "biganimal_cluster" "single_node_cluster" {
  cluster_name = var.cluster_name

  allowed_ip_ranges {
    cidr_block  = "127.0.0.1/32"
    description = "localhost"
  }

  allowed_ip_ranges {
    cidr_block  = "192.168.0.1/32"
    description = "description!"
  }

  backup_retention_period = "6d"
  cluster_architecture {
    id    = "single"
    nodes = 1
  }

  instance_type = "azure:Standard_D2s_v3"
  password      = resource.random_password.password.result
  pg_config {
    name  = "application_name"
    value = "created through terraform"
  }

  pg_config {
    name  = "array_nulls"
    value = "off"
  }

  storage {
    volume_type       = "azurepremiumstorage"
    volume_properties = "P1"
    size              = "4 Gi"
  }

  pg_type               = "epas"
  pg_version            = "14"
  private_networking    = false
  cloud_provider        = "azure"
  read_only_connections = false
  region                = "eastus2"
}

provider "biganimal" {
  ba_bearer_token = "<redacted>"
}
```

### Expected Behavior
There shouldn't be any changes pending that needs to be applied since there hasn't been any TF file changes.
Please see the output regarding "resizing_vpc" and "storage iops and throughput". 

**### Actual Behavior**
**% terraform apply**
```
random_password.password: Refreshing state... [id=none]
random_string.test: Refreshing state... [id=3w8�WEJs0enw17E/�I?�]
biganimal_cluster.single_node_cluster: Refreshing state... [id=p-kcjz6l0h77]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  biganimal_cluster.single_node_cluster will be updated in-place
  ~ resource "biganimal_cluster" "single_node_cluster" {
        id                            = "p-kcjz6l0h77"
      + resizing_pvc                  = (known after apply)
        # (15 unchanged attributes hidden)

      ~ storage {
          - iops              = "120" -> null
          - throughput        = "25" -> null
            # (3 unchanged attributes hidden)
        }

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Changes to Outputs:
    # (3 unchanged attributes hidden)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

biganimal_cluster.single_node_cluster: Modifying... [id=p-kcjz6l0h77]
biganimal_cluster.single_node_cluster: Modifications complete after 2s [id=p-kcjz6l0h77]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

MyConnectionUri = <sensitive>
MyInstanceType = <sensitive>
MyPassword = <sensitive>
MyResult = <sensitive>
```

### Steps to Reproduce
1. Create a BigAnimal single node cluster
2. Subsequent "terraform plan" and "terraform apply" commands continues to report "1 changed" in the output as shown above even though there hasn't been any TF file changes to be applied.

**Comment by serdardalgic** [comment]
The reason of this output is this: The`storage` block we provide in the example is as follows:
```
  storage {
    volume_type       = "azurepremiumstorage"
    volume_properties = "P1"
    size              = "4 Gi"
  }
  ```
It doesn't contain the `iops` and `throughput` values. Both of these values are `Optional`. 
However, those values are set after a successful creation, and because they are `Optional` instead of `Computed`, their default value is shown as they will be set to `null` in the Planning Phase. Throughput is automatically calculated according to the IOPS value, see the screenshot from the portal, when you try to create/edit a cluster:
![Screenshot 2023-01-24 at 15 36 14](https://user-images.githubusercontent.com/121254/214323069-bb0f9c02-cc73-450b-b091-b9cbd898637b.png)

So, the user would provide a different IOPS value, and that would trigger a change. But in this case, it's also not possible because the IOPS value of a single node cluster should only be 3000. 😅 (at least for AWS, I didn't check Azure yet)
![Screenshot 2023-01-24 at 15 41 50](https://user-images.githubusercontent.com/121254/214324340-99996c2e-ba09-4ed3-8ae9-966b540754ed.png)

Trying to set those values to `null` doesn't change anything in the cluster behavior in `0.2.0` version of the Biganimal terraform provider.

I think what we should do regarding this problem is:
* Check if there is a way to suppress this output when the IOPS and Throughput are not provided. 
* We can throw a validation error early for the single node clusters if the IOPS is different from 3000 because that's not possible for now for AWS. We need to check for the Azure ultra disks.  
* We can make the Throughput value `Computed`, but the IOPS should stay as `Optional`.

**Comment by serdardalgic** [comment]
We can make use of the [DiffSuppressFunc](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#diffsuppressfunc) to suppress the IOPS output.
